In [11]:
from butterfly import Butterfly
butterfly = Butterfly()

In [15]:
c_range = range(5, 20)
N_range = range(9, 24)
df_sum_before = butterfly.get_table_sum_before(c_range, N_range)
pivot_sum_before = df_sum_before.pivot(index='c', columns='logn', values='sum_before_first_c')
print(pivot_sum_before)

logn   9    10   11    12    13    14     15     16     17     18      19  \
c
5     107  235  507  1083  2299  4859  10235  21499  45051  94203  196603
6      54  122  266   570  1210  2554   5370  11258  23546  49146  102394
7      25   61  137   297   633  1337   2809   5881  12281  25593   53241
8       9   28   68   152   328   696   1464   3064   6392  13304   27640
9       0   10   31    75   167   359    759   1591   3319   6903   14327
10      0    0   11    34    82   182    390    822   1718   3574    7414
11      0    0    0    12    37    89    197    421    885   1845    3829
12      0    0    0     0    13    40     96    212    452    948    1972
13      0    0    0     0     0    14     43    103    227    483    1011
14      0    0    0     0     0     0     15     46    110    242     514
15      0    0    0     0     0     0      0     16     49    117     257
16      0    0    0     0     0     0      0      0     17     52     124
17      0    0    0     0     0     0      0      0      0     18      55
18      0    0    0     0     0     0      0      0      0      0      19
19      0    0    0     0     0     0      0      0      0      0       0

logn      20      21       22       23
c
5     409595  851963  1769467  3670011
6     212986  442362   917498  1900538
7     110585  229369   475129   983033
8      57336  118776   245752   507896
9      29687   61431   126967   262135
10     15350   31734    65526   135158
11      7925   16373    33781    69621
12      4084    8436    17396    35828
13      2099    4339     8947    18419
14      1074    2226     4594     9458
15       545    1137     2353     4849
16       272     576     1200     2480
17       131     287      607     1263
18        58     138      302      638
19        20      61      145      317

In [10]:
pivot_sum_before.to_csv('pivot_sum_before.csv')

In [ ]:
c_range = range(5, 20)
N_range = range(9, 28)
df_necessary_l = butterfly.get_table_necessary_l(c_range, N_range)
pivot_necessary_l = df_necessary_l.pivot(index='c', columns='logn', values='l')
print(pivot_necessary_l)

logn   9     10    11    12    13    14    15    16    17    18    19    20  \
c
5     9.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
6     9.0  10.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
7     9.0  10.0  10.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
8     9.0  10.0  11.0   9.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
9     9.0  10.0  11.0  12.0   8.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
10    9.0  10.0  11.0  12.0  13.0   7.0   0.0   0.0   0.0   0.0   0.0   0.0
11    9.0  10.0  11.0  12.0  13.0  14.0   6.0   0.0   0.0   0.0   0.0   0.0
12    9.0  10.0  11.0  12.0  13.0  14.0  15.0   5.0   0.0   0.0   0.0   0.0
13    9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0   4.0   0.0   0.0   0.0
14    9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0   2.0   0.0   0.0
15    9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0   0.0   0.0
16    9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0   0.0
17    9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0
18    9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0
19    NaN  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0

logn    21    22   23   24   25   26   27
c
5      0.0   0.0  0.0  0.0  0.0  0.0  0.0
6      0.0   0.0  0.0  0.0  0.0  0.0  0.0
7      0.0   0.0  0.0  0.0  0.0  0.0  0.0
8      0.0   0.0  0.0  0.0  0.0  0.0  0.0
9      0.0   0.0  0.0  0.0  0.0  0.0  0.0
10     0.0   0.0  0.0  0.0  0.0  0.0  0.0
11     0.0   0.0  0.0  0.0  0.0  0.0  0.0
12     0.0   0.0  0.0  0.0  0.0  0.0  0.0
13     0.0   0.0  0.0  0.0  0.0  0.0  0.0
14     0.0   0.0  0.0  0.0  0.0  0.0  0.0
15     0.0   0.0  0.0  0.0  0.0  0.0  0.0
16     0.0   0.0  0.0  0.0  0.0  0.0  0.0
17     0.0   0.0  0.0  0.0  0.0  0.0  0.0
18    19.0   0.0  0.0  0.0  0.0  0.0  0.0
19    21.0  18.0  0.0  0.0  0.0  0.0  0.0

In [ ]:
pivot_necessary_l.to_csv('pivot_necessary_l.csv')

In [ ]:
c_range = range(5, 20)
N_range = range(18, 28)
df_sum_before_with_l = butterfly.get_table_sum_before_with_l(c_range, N_range)
pivot_sum_before_with_l = df_sum_before_with_l.pivot(index=['c','l'], columns='logn', values='sum_before_first_c')
print(pivot_sum_before_with_l)

logn         18        19        20        21         22         23  \
c  k
5  0    94203.0  196603.0  409595.0  851963.0  1769467.0  3670011.0
   1    98299.0  204795.0  425979.0  884731.0  1835003.0  3801083.0
   2   102395.0  212987.0  442363.0  917499.0  1900539.0  3932155.0
   3   106491.0  221179.0  458747.0  950267.0  1966075.0  4063227.0
   4   110587.0  229371.0  475131.0  983035.0  2031611.0  4194299.0
...         ...       ...       ...       ...        ...        ...
19 22       NaN       NaN       NaN       NaN        NaN      619.0
   23       NaN       NaN       NaN       NaN        NaN        NaN
   24       NaN       NaN       NaN       NaN        NaN        NaN
   25       NaN       NaN       NaN       NaN        NaN        NaN
   26       NaN       NaN       NaN       NaN        NaN        NaN

logn          24          25          26          27
c  k
5  0   7602171.0  15728635.0  32505851.0  67108859.0
   1   7864315.0  16252923.0  33554427.0  69206011.0
   2   8126459.0  16777211.0  34603003.0  71303163.0
   3   8388603.0  17301499.0  35651579.0  73400315.0
   4   8650747.0  17825787.0  36700155.0  75497467.0
...          ...         ...         ...         ...
19 22     1276.0      2589.0      5214.0     10463.0
   23     1307.0      2652.0      5341.0     10718.0
   24        NaN      2715.0      5468.0     10973.0
   25        NaN         NaN      5595.0     11228.0
   26        NaN         NaN         NaN     11483.0

[405 rows x 10 columns]

In [ ]:
pivot_sum_before_with_l.to_csv('pivot_sum_before_with_l_teil_2.csv')

In [ ]:
df_anonymity_comparison = butterfly.get_table_c_anonymity_comparison(range(5,25), range(1, 20))
df_pivot = df_anonymity_comparison.pivot(index='l', columns='logn', values='c_comparison')
print(df_pivot)

logn         7          8           9           10           11           12  \
k
1     [5, 4, 5]  [7, 6, 5]   [8, 7, 7]   [7, 6, 8]    [8, 7, 7]  [11, 10, 8]
2     [5, 4, 5]  [8, 6, 5]   [7, 5, 7]   [8, 6, 8]   [11, 9, 7]   [11, 9, 8]
3     [6, 4, 5]  [7, 4, 5]   [8, 5, 7]  [11, 8, 8]   [11, 8, 7]  [13, 10, 8]
4     [8, 5, 5]  [8, 5, 5]  [11, 7, 7]  [11, 7, 8]   [13, 9, 7]   [13, 9, 8]
5     [9, 5, 5]  [8, 5, 5]  [10, 6, 7]  [13, 8, 8]   [13, 8, 7]  [15, 10, 8]
6     [6, 3, 5]  [9, 5, 5]  [11, 6, 7]  [12, 7, 8]   [15, 9, 7]  [16, 10, 8]
7           NaN  [8, 4, 5]  [12, 7, 7]  [14, 8, 8]   [15, 9, 7]   [15, 8, 8]
8           NaN        NaN  [12, 6, 7]  [15, 8, 8]  [17, 10, 7]   [16, 8, 8]
9           NaN        NaN         NaN  [16, 8, 8]   [14, 7, 7]   [17, 9, 8]
10          NaN        NaN         NaN         NaN   [14, 7, 7]   [17, 9, 8]
11          NaN        NaN         NaN         NaN          NaN   [18, 9, 8]
12          NaN        NaN         NaN         NaN          NaN          NaN
13          NaN        NaN         NaN         NaN          NaN          NaN
14          NaN        NaN         NaN         NaN          NaN          NaN
15          NaN        NaN         NaN         NaN          NaN          NaN
16          NaN        NaN         NaN         NaN          NaN          NaN
17          NaN        NaN         NaN         NaN          NaN          NaN
18          NaN        NaN         NaN         NaN          NaN          NaN
19          NaN        NaN         NaN         NaN          NaN          NaN

logn            13            14            15            16            17  \
k
1     [11, 10, 11]  [13, 12, 11]  [13, 12, 13]  [15, 14, 13]  [16, 15, 15]
2     [13, 11, 11]  [13, 11, 11]  [15, 13, 13]  [16, 14, 13]  [15, 13, 15]
3     [13, 10, 11]  [15, 12, 11]  [16, 13, 13]  [15, 12, 13]  [16, 13, 15]
4     [15, 11, 11]  [16, 12, 11]  [15, 11, 13]  [16, 12, 13]  [18, 14, 15]
5     [16, 11, 11]  [15, 10, 11]  [16, 11, 13]  [18, 13, 13]  [19, 14, 15]
6      [15, 9, 11]  [16, 10, 11]  [18, 12, 13]  [19, 13, 13]  [20, 14, 15]
7      [16, 9, 11]  [18, 11, 11]  [19, 12, 13]  [20, 13, 13]  [22, 15, 15]
8     [18, 10, 11]  [19, 11, 11]  [20, 12, 13]  [22, 14, 13]  [22, 14, 15]
9     [19, 10, 11]  [20, 11, 11]  [22, 13, 13]  [22, 13, 13]  [23, 14, 15]
10    [19, 10, 11]  [22, 12, 11]  [22, 12, 13]  [23, 13, 13]  [24, 14, 15]
11    [20, 11, 11]  [22, 12, 11]  [23, 12, 13]  [24, 13, 13]  [26, 15, 15]
12    [21, 11, 11]  [22, 11, 11]  [23, 12, 13]  [26, 14, 13]  [27, 15, 15]
13             NaN  [22, 11, 11]  [25, 13, 13]  [26, 14, 13]  [28, 15, 15]
14             NaN           NaN  [25, 13, 13]  [27, 14, 13]  [28, 15, 15]
15             NaN           NaN           NaN  [28, 14, 13]  [29, 15, 15]
16             NaN           NaN           NaN           NaN  [30, 15, 15]
17             NaN           NaN           NaN           NaN           NaN
18             NaN           NaN           NaN           NaN           NaN
19             NaN           NaN           NaN           NaN           NaN

logn            18            19            20            21            22  \
k
1     [15, 14, 16]  [16, 15, 15]  [18, 17, 16]  [19, 18, 18]  [20, 19, 19]
2     [16, 14, 16]  [18, 16, 15]  [19, 17, 16]  [20, 18, 18]  [22, 20, 19]
3     [18, 15, 16]  [19, 16, 15]  [20, 17, 16]  [22, 19, 18]  [22, 19, 19]
4     [19, 15, 16]  [20, 16, 15]  [22, 18, 16]  [22, 18, 18]  [23, 19, 19]
5     [20, 15, 16]  [22, 17, 15]  [22, 17, 16]  [23, 18, 18]  [24, 19, 19]
6     [22, 16, 16]  [22, 16, 15]  [23, 17, 16]  [24, 18, 18]  [26, 20, 19]
7     [22, 15, 16]  [23, 16, 15]  [24, 17, 16]  [26, 19, 18]  [27, 20, 19]
8     [23, 15, 16]  [24, 16, 15]  [26, 18, 16]  [27, 19, 18]  [28, 20, 19]
9     [24, 15, 16]  [26, 17, 15]  [27, 18, 16]  [28, 19, 18]  [29, 20, 19]
10    [26, 16, 16]  [27, 17, 15]  [28, 18, 16]  [29, 19, 18]  [30, 20, 19]
11    [27, 16, 16]  [28, 17, 15]  [29, 18, 16]  [30, 19, 18]  [31, 20, 19]
12    [28, 16, 16]  [29, 17, 15]  [30, 18, 16]  [31, 19, 18]  [33, 21, 19]
13    [29, 16, 16]  [30, 17, 15]  [31, 18, 16]  [33, 20, 18]  [34, 21, 19]
14    [30, 16, 16]  [31, 17, 15]  [33, 19, 16]  [34, 20, 18]  [35, 21, 19]
15    [30, 16, 16]  [33, 18, 15]  [34, 19, 16]  [35, 20, 18]  [36, 21, 19]
16    [31, 16, 16]  [33, 18, 15]  [35, 19, 16]  [36, 20, 18]  [35, 19, 19]
17    [33, 17, 16]  [34, 18, 15]  [35, 19, 16]  [35, 18, 18]  [36, 19, 19]
18             NaN  [35, 18, 15]  [36, 19, 16]  [36, 18, 18]  [37, 19, 19]
19             NaN           NaN  [34, 17, 16]  [36, 18, 18]  [38, 19, 19]

logn            23            24
k
1     [22, 21, 20]  [22, 21, 22]
2     [22, 20, 20]  [23, 21, 22]
3     [23, 20, 20]  [24, 21, 22]
4     [24, 20, 20]  [26, 22, 22]
5     [26, 21, 20]  [27, 22, 22]
6     [27, 21, 20]  [28, 22, 22]
7     [28, 21, 20]  [29, 22, 22]
8     [29, 21, 20]  [30, 22, 22]
9     [30, 21, 20]  [31, 22, 22]
10    [31, 21, 20]  [33, 23, 22]
11    [33, 22, 20]  [34, 23, 22]
12    [34, 22, 20]  [35, 23, 22]
13    [35, 22, 20]  [36, 23, 22]
14    [36, 22, 20]  [35, 21, 22]
15    [35, 20, 20]  [36, 21, 22]
16    [36, 20, 20]  [37, 21, 22]
17    [37, 20, 20]  [38, 21, 22]
18    [38, 20, 20]  [39, 21, 22]
19    [39, 20, 20]  [40, 21, 22]